//! Game library model and persistence.
//!
//! Provider-scanned titles (Steam, Heroic, desktop entries) are merged with a
//! local metadata store so user data (favorites, playtime, last played) is
//! never lost when a scan changes.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::launcher::Spec;
use crate::util;

/// How a library entry is launched.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Default)]
#[serde(tag = "kind", content = "args", rename_all = "snake_case")]
pub enum Launch {
    /// Plain native command.
    Program { program: String, args: Vec<String> },
    /// Steam game by app id.
    Steam { app_id: String },
    /// Heroic / legendary game by app name.
    Heroic { app_name: String },
    /// Not launchable (e.g. placeholder section header).
    #[default]
    None,
}

impl Launch {
    pub fn to_spec(&self, name: &str, steam_bin: Option<&str>) -> Option<Spec> {
        match self {
            Launch::Program { program, args } => Some(Spec::new(name, program).args(args.clone())),
            Launch::Steam { app_id } => {
                let bin = steam_bin.unwrap_or("steam");
                Some(Spec::new(name, bin).arg("-applaunch").arg(app_id))
            }
            Launch::Heroic { app_name } => {
                // Prefer `legendary` (no GUI dependency) then `heroic`.
                if which_ok("legendary") {
                    return Some(Spec::new(name, "legendary").arg("launch").arg(app_name));
                }
                Some(Spec::new(name, "heroic").arg("-l").arg(app_name))
            }
            Launch::None => None,
        }
    }
}

fn which_ok(name: &str) -> bool {
    std::process::Command::new("sh")
        .arg("-c")
        .arg(format!("command -v {name} >/dev/null 2>&1"))
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// One entry shown in the library UI.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Game {
    /// Stable id: "<source>-<key>", e.g. "steam-570", "heroic-LambdaRule",
    /// "desktop-firefox.desktop".
    pub id: String,
    pub title: String,
    /// Provider id: "manual" | "steam" | "heroic" | "desktop" | "native".
    pub source: String,
    #[serde(default)]
    pub launch: Launch,
    /// Optional icon path (will be generated by the UI if missing).
    #[serde(default)]
    pub icon: Option<PathBuf>,
    /// Optional large artwork path.
    #[serde(default)]
    pub artwork: Option<PathBuf>,
    /// Unix timestamp of last launch.
    #[serde(default)]
    pub last_played: Option<i64>,
    #[serde(default)]
    pub playtime_secs: u64,
    #[serde(default)]
    pub favorite: bool,
    #[serde(default = "default_true")]
    pub installed: bool,
    /// Console / device a curated app targets, e.g. "PS2" or "Wii".
    #[serde(default)]
    pub platform: Option<String>,
    /// ROM file extensions this emulator tile can boot (empty for normal apps).
    #[serde(default)]
    pub rom_exts: Vec<String>,
}

fn default_true() -> bool {
    true
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct Library {
    #[serde(default)]
    pub games: BTreeMap<String, Game>,
}

impl Library {
    pub fn path() -> PathBuf {
        util::data_dir().join("library.json")
    }

    pub fn load() -> Library {
        let p = Self::path();
        match std::fs::read_to_string(&p) {
            Ok(text) => serde_json::from_str(&text).unwrap_or_else(|e| {
                log::warn!("Library at {} invalid ({e}); starting fresh.", p.display());
                Library::default()
            }),
            Err(_) => Library::default(),
        }
    }

    pub fn save(&self) -> Result<()> {
        util::ensure_dir(&util::data_dir())?;
        let p = Self::path();
        let tmp = p.with_extension("json.tmp");
        std::fs::write(&tmp, serde_json::to_string_pretty(self)?)?;
        std::fs::rename(&tmp, &p)?;
        Ok(())
    }

    /// Merge provider candidates into the library, preserving user metadata
    /// for games that already exist.
    pub fn merge(&mut self, candidates: Vec<Game>) {
        for mut cand in candidates {
            if let Some(existing) = self.games.remove(&cand.id) {
                cand.last_played = existing.last_played.or(cand.last_played);
                cand.playtime_secs = existing.playtime_secs.max(cand.playtime_secs);
                cand.favorite = cand.favorite || existing.favorite;
                if cand.icon.is_none() {
                    cand.icon = existing.icon;
                }
            }
            self.games.insert(cand.id.clone(), cand);
        }
    }

    /// Remove library entries not seen in the current scan (games removed on disk).
    pub fn prune_missing(&mut self, seen_ids: &std::collections::HashSet<String>, manual_keep: bool) {
        let keys: Vec<String> = self.games.keys().cloned().collect();
        for id in keys {
            let keep_manual = manual_keep && self.games[&id].source == "manual";
            if seen_ids.contains(&id) || keep_manual {
                continue;
            }
            self.games.remove(&id);
        }
    }

    pub fn all_sorted(&self) -> Vec<Game> {
        let mut v: Vec<Game> = self.games.values().cloned().collect();
        v.sort_by(|a, b| {
            b.last_played
                .unwrap_or(0)
                .cmp(&a.last_played.unwrap_or(0))
                .then_with(|| a.title.cmp(&b.title))
        });
        v
    }

    pub fn by_source(&self, source: &str) -> Vec<Game> {
        self.games
            .values()
            .filter(|g| g.source == source)
            .cloned()
            .collect()
    }

    pub fn favorites(&self) -> Vec<Game> {
        self.games
            .values()
            .filter(|g| g.favorite)
            .cloned()
            .collect()
    }

    pub fn recently_played(&self, n: usize) -> Vec<Game> {
        let mut v = self
            .games
            .values()
            .filter(|g| g.last_played.is_some())
            .cloned()
            .collect::<Vec<_>>();
        v.sort_by_key(|g| std::cmp::Reverse(g.last_played.unwrap_or(0)));
        v.truncate(n);
        v
    }

    pub fn get(&self, id: &str) -> Option<&Game> {
        self.games.get(id)
    }

    pub fn set_favorite(&mut self, id: &str, fav: bool) -> Result<()> {
        if let Some(g) = self.games.get_mut(id) {
            g.favorite = fav;
            self.save()
        } else {
            Err(anyhow::anyhow!("no such game: {id}"))
        }
    }

    pub fn record_launch(&mut self, id: &str) -> Result<()> {
        if let Some(g) = self.games.get_mut(id) {
            g.last_played = Some(util::unix_now());
            self.save()
        } else {
            Err(anyhow::anyhow!("no such game: {id}"))
        }
    }

    pub fn add_playtime(&mut self, id: &str, secs: u64) -> Result<()> {
        if let Some(g) = self.games.get_mut(id) {
            g.playtime_secs += secs;
            self.save()
        } else {
            Err(anyhow::anyhow!("no such game: {id}"))
        }
    }

    /// Add or replace a manually-defined game.
    pub fn add_manual(&mut self, game: Game) -> Result<()> {
        self.merge(vec![game]);
        self.save()
    }

    pub fn remove(&mut self, id: &str) -> Result<()> {
        self.games.remove(id);
        self.save()
    }

    pub fn delete_key(&mut self, id: &str) -> Result<()> {
        self.remove(id)
    }
}

/// Nice printable playtime ("12 h 30 m") helpers.
pub fn format_playtime(secs: u64) -> String {
    if secs == 0 {
        return "Never played".to_string();
    }
    let h = secs / 3600;
    let m = (secs % 3600) / 60;
    if h > 0 {
        format!("{h} h {m:02} m")
    } else {
        format!("{m} m")
    }
}

pub fn format_last_played(ts: i64) -> String {
    let now = util::unix_now();
    let diff = (now - ts).max(0) as u64;
    let day = 86_400;
    if diff == 0 {
        "Just now".to_string()
    } else if diff < 3600 {
        format!("{} min ago", diff / 60 + 1)
    } else if diff < day {
        format!("{} h ago", diff / 3600)
    } else {
        format!("{} d ago", diff / day)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, MutexGuard, OnceLock};

    /// Serialises tests that mutate the NOVASHELL_* env vars so parallel
    /// test threads can't see each other's directories.
    fn iso_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    struct IsoDirs {
        _guard: MutexGuard<'static, ()>,
        _data: tempfile::TempDir,
        _config: tempfile::TempDir,
    }

    fn with_isolated_dirs() -> IsoDirs {
        let guard = iso_lock().lock().unwrap();
        let data = tempfile::tempdir().unwrap();
        let config = tempfile::tempdir().unwrap();
        std::env::set_var("NOVASHELL_DATA_DIR", data.path());
        std::env::set_var("NOVASHELL_CONFIG_DIR", config.path());
        IsoDirs {
            _guard: guard,
            _data: data,
            _config: config,
        }
    }

    fn g(id: &str, source: &str, title: &str) -> Game {
        Game {
            id: id.to_string(),
            title: title.to_string(),
            source: source.to_string(),
            launch: Launch::None,
            icon: None,
            artwork: None,
            last_played: None,
            playtime_secs: 0,
            favorite: false,
            installed: true,
            platform: None,
            rom_exts: Vec::new(),
        }
    }

    #[test]
    fn merge_preserves_metadata() {
        let _iso = with_isolated_dirs();
        let mut lib = Library::default();
        lib.add_manual(g("steam-570", "steam", "Dota 2")).unwrap();
        lib.set_favorite("steam-570", true).unwrap();
        lib.record_launch("steam-570").unwrap();
        lib.add_playtime("steam-570", 3600).unwrap();

        // Re-scan sees the same game; metadata must survive.
        lib.merge(vec![g("steam-570", "steam", "Dota 2")]);
        let game = lib.get("steam-570").unwrap();
        assert!(game.favorite);
        assert!(game.last_played.is_some());
        assert_eq!(game.playtime_secs, 3600);
    }

    #[test]
    fn prune_drops_missing_but_keeps_manual() {
        let _iso = with_isolated_dirs();
        let mut lib = Library::default();
        lib.add_manual(g("steam-1", "steam", "A")).unwrap();
        lib.add_manual(g("m-1", "manual", "My game")).unwrap();

        let mut seen = std::collections::HashSet::new();
        seen.insert("steam-2".to_string());
        lib.prune_missing(&seen, true);
        assert!(lib.get("m-1").is_some());
        assert!(lib.get("steam-1").is_none());
    }

    #[test]
    fn playtime_format() {
        assert_eq!(format_playtime(0), "Never played");
        assert_eq!(format_playtime(7200 + 12 * 60), "2 h 12 m");
        assert_eq!(format_playtime(600), "10 m");
    }

    #[test]
    fn steam_launch_spec() {
        let l = Launch::Steam {
            app_id: "570".to_string(),
        };
        let spec = l.to_spec("Dota 2", Some("/usr/bin/steam")).unwrap();
        assert_eq!(spec.program, "/usr/bin/steam");
        assert_eq!(spec.args, vec!["-applaunch", "570"]);
    }
}